spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.h2.console.enabled=false
spring.thymeleaf.cache=true

server.servlet.session.persistent=false
