create table warehouses (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    address varchar(255) not null
);

create table items (
    id bigint generated by default as identity primary key,
    barcode varchar(64) not null,
    name varchar(150) not null,
    brand varchar(100) not null,
    type varchar(100) not null,
    constraint uk_items_barcode unique (barcode)
);

create table warehouse_items (
    id bigint generated by default as identity primary key,
    warehouse_id bigint not null,
    item_id bigint not null,
    quantity integer not null,
    constraint fk_warehouse_items_warehouse foreign key (warehouse_id) references warehouses (id),
    constraint fk_warehouse_items_item foreign key (item_id) references items (id),
    constraint uk_warehouse_items_warehouse_item unique (warehouse_id, item_id),
    constraint ck_warehouse_items_quantity_non_negative check (quantity >= 0)
);

create table orders (
    id bigint generated by default as identity primary key,
    status varchar(20) not null,
    constraint ck_orders_status check (status in ('REQUIRED', 'APPROVED', 'REJECTED', 'CANCELED'))
);

create table order_status_events (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    from_status varchar(20),
    to_status varchar(20) not null,
    authorized_by_user_id varchar(100) not null,
    authorized_at timestamp not null,
    reason varchar(500),
    constraint fk_order_status_events_order foreign key (order_id) references orders (id),
    constraint ck_order_status_events_from_status check (from_status is null or from_status in ('REQUIRED', 'APPROVED', 'REJECTED', 'CANCELED')),
    constraint ck_order_status_events_to_status check (to_status in ('REQUIRED', 'APPROVED', 'REJECTED', 'CANCELED'))
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    item_id bigint not null,
    warehouse_id bigint not null,
    quantity integer not null,
    constraint fk_order_items_order foreign key (order_id) references orders (id),
    constraint fk_order_items_item foreign key (item_id) references items (id),
    constraint fk_order_items_warehouse foreign key (warehouse_id) references warehouses (id),
    constraint ck_order_items_quantity_positive check (quantity > 0)
);

create index idx_warehouse_items_item on warehouse_items (item_id);
create index idx_order_items_order on order_items (order_id);
create index idx_orders_status on orders (status);
create index idx_order_status_events_order on order_status_events (order_id);
create index idx_order_status_events_authorized_at on order_status_events (authorized_at);
