create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(100) not null,
    display_name varchar(150) not null,
    password_hash varchar(255) not null,
    role varchar(30) not null,
    enabled boolean not null,
    constraint uk_app_users_username unique (username),
    constraint ck_app_users_role check (role in ('ADMIN', 'STORE_MANAGER', 'USER'))
);

create index idx_app_users_role on app_users (role);
